
$(function(){$('#nav-accordion').dcAccordion({eventType:'click',autoClose:true,saveState:true,disableLink:true,speed:'slow',showCount:false,autoExpand:true,classExpand:'dcjq-current-parent'});});var Script=function(){jQuery('#sidebar .sub-menu > a').click(function(){var o=($(this).offset());diff=250-o.top;if(diff>0)
$("#sidebar").scrollTo("-="+Math.abs(diff),500);else
$("#sidebar").scrollTo("+="+Math.abs(diff),500);});$(function(){function responsiveView(){var wSize=$(window).width();if(wSize<=768){$('#container').addClass('sidebar-close');$('#sidebar > ul').hide();}
if(wSize>768){$('#container').removeClass('sidebar-close');$('#sidebar > ul').show();}}
$(window).on('load',responsiveView);$(window).on('resize',responsiveView);});$('.fa-bars').click(function(){if($('#sidebar > ul').is(":visible")===true){$('#main-content').css({'margin-left':'0px'});$('#sidebar').css({'margin-left':'-210px'});$('#sidebar > ul').hide();$("#container").addClass("sidebar-closed");}else{$('#main-content').css({'margin-left':'210px'});$('#sidebar > ul').show();$('#sidebar').css({'margin-left':'0'});$("#container").removeClass("sidebar-closed");}});jQuery('.panel .tools .fa-chevron-down').click(function(){var el=jQuery(this).parents(".panel").children(".panel-body");if(jQuery(this).hasClass("fa-chevron-down")){jQuery(this).removeClass("fa-chevron-down").addClass("fa-chevron-up");el.slideUp(200);}else{jQuery(this).removeClass("fa-chevron-up").addClass("fa-chevron-down");el.slideDown(200);}});jQuery('.panel .tools .fa-times').click(function(){jQuery(this).parents(".panel").parent().remove();});$('.tooltips').tooltip();$('.popovers').popover();if($(".custom-bar-chart")){$(".bar").each(function(){var i=$(this).find(".value").html();$(this).find(".value").html("");$(this).find(".value").animate({height:i},2000)})}}();
(function($,undefined){$.extend({user:{setup:function(){$.m.user.wallet={};$.m.user.img={};$.m.user.img.qr=new Image();$.m.user.img.qr.src="img/css/qr.png";$.m.user.img.qrp=new Image();$.m.user.img.qrp.src="img/css/qrp.png";$('#'+$.m.div.content).mustache('txModal',$.m);},homePage:function(){$.tmpl.clean();if(!$('#sidebarHome').length)$('#'+$.m.div.mRight).empty().mustache('sidebarHome',$.m);$('#'+$.m.div.mRight+' .sub-menu').each(function(){$(this).mouseenter(function(){$.voix.play($.m.voix.sound.btnOver);});});if($.m.user.wallet.adr){$('#'+$.m.div.page).empty().mustache('wallet',$.m);$('#qrCodeAdr').qrcode({text:'bitcoin:'+$.m.user.wallet.adr,render:'canvas',minVersion:2,maxVersion:20,ecLevel:'H',top:0,size:250,fill:'#333333',background:null,radius:0.5,mode:4,mSize:0.2,mPosX:0.5,mPosY:0.5,image:$.m.user.img.qr,});}
else{$('#'+$.m.div.page).empty().mustache('userHomePage',$.m);$('#formLogin').validate();$('#formLogin').on('formLogin',$.user.sendLogin);$('#formLogin #passPhrase').keyup($.user.passPhraseControl);$('#'+$.m.div.page+' span').tooltip();}},passPhraseControl:function(){var anUpperCase=/[A-ZÉÈÄËÏÖÜŸÃÑÊÕÀÁÂÎÃÔÒÓÇÝÛÚÙÆ]/;var aLowerCase=/[a-zéèçàôùúûîêäëïöüÿãñõœ]/;var aNumber=/[0-9]/;var aSpecial=/[ !@#$%^&*()\-\/_\'"§;.,:+\=]/;var Resultat=0;if(!$('#formLogin #passPhrase').val())$('#messDangerPhrase').empty();else{var p=$('#formLogin #passPhrase').val();var numUpper=0;var numLower=0;var numNums=0;var numSpecials=0;var numLongeur=p.length;var PassScore=0
for(var i=0;i<p.length;i++){if(anUpperCase.test(p[i]))numUpper++;else if(aLowerCase.test(p[i]))numLower++;else if(aNumber.test(p[i]))numNums++;else if(aSpecial.test(p[i]))numSpecials++;}
if(numLongeur<10)PassScore-=3;else PassScore+=Math.floor(numLongeur/10);if(numSpecials<1)PassScore-=1;else PassScore+=Math.floor(numSpecials/2);if(numUpper*10<numLongeur)PassScore-=Math.floor(numLongeur/20);else PassScore+=Math.floor(numUpper/3);if(numNums*10<numLongeur)PassScore-=Math.floor(numLongeur/20);else PassScore+=Math.floor(numNums/3);if(numLower*5<numLongeur)PassScore-=Math.floor(numLongeur/20);else PassScore+=Math.floor(numLower/4);if(PassScore<=20){$.m.user.messPass={"alert":"danger","icone":"ban","message":"PHRASE_DANGER"};$('#messDangerPhrase').empty().mustache('messDangerPhraseHTML',$.m);}
else if(PassScore<=40){$.m.user.messPass={"alert":"warning","icone":"exclamation-triangle","message":"PHRASE_WARNING"};$('#messDangerPhrase').empty().mustache('messDangerPhraseHTML',$.m);}
else{$.m.user.messPass={"alert":"success","icone":"check","message":"PHRASE_SUCCES"};$('#messDangerPhrase').empty().mustache('messDangerPhraseHTML',$.m);}}},keyHTML:function(){if($.m.user.wallet.adr){$.tmpl.clean();$('#'+$.m.div.page).empty().mustache('keyHTML',$.m);$('#formKey').validate();$('#formKey').on('formKey',$.user.keyFUNC);}
else $.tmpl.error('WARNING_NOT_CONNECTED');},keyFUNC:function(){if($.m.user.wallet.adr){var hash=Crypto.util.hexToBytes($.crp.decrypte($.m.user.wallet.hash,$.sha1($('#formKey #password').val())));var sec=new Bitcoin.ECKey(hash);var adr=''+sec.getBitcoinAddress();if($.m.user.wallet.adr==adr){var key=''+sec.getExportedPrivateKey();$('#keyQrCode').empty().mustache('QrPrivatKeyPart',$.m);$('#keyText').html('<i class="fa fa-key"></i> '+key);$('#qrKeyCodeAdr').qrcode({text:key,render:'canvas',minVersion:5,maxVersion:20,ecLevel:'H',top:0,size:250,fill:'#333333',background:null,radius:0.5,mode:4,mSize:0.2,mPosX:0.5,mPosY:0.5,image:$.m.user.img.qrp,});$.voix.play($.m.voix.sound.click);sec='';hash='';key='';}
else{$.tmpl.error('FORM_WARNING_ADDR_BTC_INVALID');$.user.homePage();}}
else $.tmpl.error('WARNING_NOT_CONNECTED');},signHTML:function(){if($.m.user.wallet.adr){$.tmpl.clean();$('#'+$.m.div.page).empty().mustache('signHTML',$.m);$('#formSignMess').validate();$('#formSignMess').on('formSignMess',$.user.signFUNC);}
else $.tmpl.error('WARNING_NOT_CONNECTED');},signFUNC:function(){if($.m.user.wallet.adr){var hash=Crypto.util.hexToBytes($.crp.decrypte($.m.user.wallet.hash,$.sha1($('#formSignMess #password').val())));var sec=new Bitcoin.ECKey(hash);var adr=''+sec.getBitcoinAddress();var key=''+sec.getExportedPrivateKey();var payload=Bitcoin.Base58.decode(key);var compressed=payload.length==38;if($.m.user.wallet.adr==adr){$.m.user.wallet.mess=$('#formSignMess #mess').val();$.m.user.wallet.sign=$.user.sign_message(sec,$.m.user.wallet.mess,compressed);if($.m.user.wallet.sign){$('#signMess').empty().mustache('goodSignPart',$.m);$.voix.play($.m.voix.sound.click);sec='';}
else{sec='';$.tmpl.error('WARNING_SIGN_MESS_ERR');}}
else $.tmpl.error('FORM_WARNING_ADDR_BTC_INVALID');}
else $.tmpl.error('WARNING_NOT_CONNECTED');},verifHTML:function(){$.tmpl.clean();$('#'+$.m.div.page).empty().mustache('verifHTML',$.m);$('#formVerif').validate();$('#formVerif').on('formVerif',$.user.verifFUNC);$('#'+$.m.div.page+' span').tooltip();},verifFUNC:function(){if($.user.verify_message($('#formVerif #sign').val(),$('#formVerif #mess').val())==$('#formVerif #btcadr').val()){$('#verifMess').empty().mustache('valideSignPart',$.m);$.voix.play($.m.voix.sound.click);setTimeout(function(){$('#verifMess').empty().mustache('verifDefautPart',$.m);},3000);}
else $.tmpl.error('WARNING_SIGN_INVALID');},sendLogin:function(){if(!$.m.user.wallet.adr){var hash=Crypto.SHA256($('#formLogin #passPhrase').val(),{asBytes:true});var sec=new Bitcoin.ECKey(hash);$.m.user.wallet.adr=''+sec.getBitcoinAddress();$.m.user.wallet.hash=$.crp.crypte(Crypto.util.bytesToHex(hash),$.sha1($('#formLogin #password').val()));sec='';$('#'+$.m.div.event).trigger('login');$('#'+$.m.div.mRight).empty();$.user.homePage();$.voix.play($.m.voix.sound.click);}
else $.tmpl.error('WARNING_CONNECTED');},sendLogout:function(){if($.m.user.wallet.adr){$.m.user.wallet={};$('#'+$.m.div.mRight).empty();$.user.homePage();$('#'+$.m.div.event).trigger('logout');}
else $.tmpl.error('WARNING_NOT_CONNECTED');},sign_message:function(private_key,message,compressed,addrtype){function msg_numToVarInt(i){if(i<0xfd){return[i];}else if(i<=0xffff){return[0xfd,i&255,i>>>8];}else{throw("message too large");}}
function msg_bytes(message){var b=Crypto.charenc.UTF8.stringToBytes(message);return msg_numToVarInt(b.length).concat(b);}
function msg_digest(message){var b=msg_bytes("Bitcoin Signed Message:\n").concat(msg_bytes(message));return Crypto.SHA256(Crypto.SHA256(b,{asBytes:true}),{asBytes:true});}
if(!private_key)return false;var signature=private_key.sign(msg_digest(message));var address=new Bitcoin.Address(private_key.getPubKeyHash());address.version=addrtype?addrtype:0;var obj=Bitcoin.ECDSA.parseSig(signature);var sequence=[0];sequence=sequence.concat(obj.r.toByteArrayUnsigned());sequence=sequence.concat(obj.s.toByteArrayUnsigned());for(var i=0;i<4;i++){var nV=27+i;if(compressed)
nV+=4;sequence[0]=nV;var sig=Crypto.util.bytesToBase64(sequence);if($.user.verify_message(sig,message,addrtype)==address)return sig;}
return false;},verify_message:function(signature,message,addrtype){function msg_numToVarInt(i){if(i<0xfd){return[i];}else if(i<=0xffff){return[0xfd,i&255,i>>>8];}else{throw("message too large");}}
function msg_bytes(message){var b=Crypto.charenc.UTF8.stringToBytes(message);return msg_numToVarInt(b.length).concat(b);}
function msg_digest(message){var b=msg_bytes("Bitcoin Signed Message:\n").concat(msg_bytes(message));return Crypto.SHA256(Crypto.SHA256(b,{asBytes:true}),{asBytes:true});}
try{var sig=Crypto.util.base64ToBytes(signature);}catch(err){return false;}
if(sig.length!=65)return false;var r=BigInteger.fromByteArrayUnsigned(sig.slice(1,1+32));var s=BigInteger.fromByteArrayUnsigned(sig.slice(33,33+32));var compressed=false;var nV=sig[0];if(nV<27||nV>=35)return false;if(nV>=31){compressed=true;nV-=4;}
var recid=BigInteger.valueOf(nV-27);var ecparams=getSECCurveByName("secp256k1");var curve=ecparams.getCurve();var a=curve.getA().toBigInteger();var b=curve.getB().toBigInteger();var p=curve.getQ();var G=ecparams.getG();var order=ecparams.getN();var x=r.add(order.multiply(recid.divide(BigInteger.valueOf(2))));var alpha=x.multiply(x).multiply(x).add(a.multiply(x)).add(b).mod(p);var beta=alpha.modPow(p.add(BigInteger.ONE).divide(BigInteger.valueOf(4)),p);var y=beta.subtract(recid).isEven()?beta:p.subtract(beta);var R=new ECPointFp(curve,curve.fromBigInteger(x),curve.fromBigInteger(y));var e=BigInteger.fromByteArrayUnsigned(msg_digest(message));var minus_e=e.negate().mod(order);var inv_r=r.modInverse(order);var Q=(R.multiply(s).add(G.multiply(minus_e))).multiply(inv_r);var public_key=Q.getEncoded(compressed);var addr=new Bitcoin.Address(Bitcoin.Util.sha256ripe160(public_key));addr.version=addrtype?addrtype:0;return addr.toString();},}});})(jQuery);
(function($,undefined){$.extend({home:{setup:function(){$.m.home.free={};$.m.home.obs={};$.home.homePage();},homePage:function(){$.tmpl.clean();if(!$('#sidebarHome').length)$('#'+$.m.div.mRight).empty().mustache('sidebarHome',$.m);$('#'+$.m.div.mRight+' .sub-menu').each(function(){$(this).mouseenter(function(){$.voix.play($.m.voix.sound.btnOver);});});$('#'+$.m.div.page).empty().mustache('homePage',$.m);},paperWalletPage:function(){$.tmpl.clean();$('#'+$.m.div.page).empty().mustache('paperWalletPage',$.m);$('#formPaperWallet').validate();$('#formPaperWallet').on('formPaperWallet',$.home.paperWalletFunc);$('#formPaperWallet #passPhrase').keyup($.home.passPhraseControl);},paperWalletFunc:function(){$('.btnInitPaperWallet').attr("disabled","disabled");$.tmpl.spinOn("btnInitPaperWalletIcone","fa-magic");function wrapText(context,text,x,y,maxWidth,lineHeight){var words=text.split('');var line='';for(var n=0;n<words.length;n++){var testLine=line+words[n];var metrics=context.measureText(testLine);var testWidth=metrics.width;if(testWidth>maxWidth&&n>0){context.fillText(line,x,y);line=words[n];y+=lineHeight;}
else{line=testLine;}}
context.fillText(line,x,y);}
var hash=Crypto.SHA256($('#formPaperWallet #passPhrase').val(),{asBytes:true});var sec=new Bitcoin.ECKey(hash);var addr=''+sec.getBitcoinAddress();var key=''+sec.getExportedPrivateKey();var canvas=document.createElement("canvas");canvas.width=2480;canvas.height=3508;var context=canvas.getContext('2d');var qrAddrObj=new Image();qrAddrObj.src=$.home.qrCodeInit('bitcoin:'+addr);var qrKeyObj=new Image();qrKeyObj.src=$.home.qrCodeInit(key);var qrPassObj=new Image();qrPassObj.src=$.home.qrCodeInit($('#formPaperWallet #passPhrase').val());var imgFond=new Image();imgFond.onload=function(){context.drawImage(imgFond,0,0);context.drawImage(qrAddrObj,545,795);context.drawImage(qrPassObj,630,3050);context.drawImage(qrKeyObj,2035,3050);context.font='19pt Arial';context.fillStyle='#333333';context.fillText(addr,20,1160);wrapText(context,key,1550,3125,320,30);wrapText(context,$('#formPaperWallet #passPhrase').val(),1110,3125,320,30);context.translate(2480,3508);context.rotate(180*(Math.PI/180));context.drawImage(qrAddrObj,545,795);context.drawImage(qrPassObj,630,3050);context.drawImage(qrKeyObj,2035,3050);context.fillText(addr,20,1160);wrapText(context,key,1550,3125,320,30);wrapText(context,$('#formPaperWallet #passPhrase').val(),1110,3125,320,30);context.restore();var dataURL=canvas.toDataURL('image/jpeg',0.9);var img='<a href="'+dataURL+'" download="PaperWallet.jpg" target="_blank"><img class="img-responsive img-thumbnail" src="'+dataURL+'" alt="Bitcoin Paper Wallet"></a>';$('#imgWallet').empty().html(img);$('.btnInitPaperWallet').removeAttr("disabled");$.tmpl.spinOff("btnInitPaperWalletIcone","fa-magic");}
if($('#formPaperWallet #colorPaperWallet:checked').val()=='blue')imgFond.src="img/btc/paperWallet.jpg";else if($('#formPaperWallet #colorPaperWallet:checked').val()=='orange')imgFond.src="img/btc/paperWalletOrange.jpg";else if($('#formPaperWallet #colorPaperWallet:checked').val()=='green')imgFond.src="img/btc/paperWalletGreen.jpg";else if($('#formPaperWallet #colorPaperWallet:checked').val()=='rose')imgFond.src="img/btc/paperWalletRose.jpg";else imgFond.src="img/btc/paperWallet.jpg";},qrCodeInit:function(e){var qrAddr=$('<div id="qrDiv"></div>');qrAddr.qrcode({text:e,render:'image',minVersion:2,maxVersion:20,ecLevel:'H',top:0,size:300,fill:'#333333',background:null,radius:0.5,mode:0});return qrAddr[0].children[0].src;},passPhraseControl:function(){var anUpperCase=/[A-ZÉÈÄËÏÖÜŸÃÑÊÕÀÁÂÎÃÔÒÓÇÝÛÚÙÆ]/;var aLowerCase=/[a-zéèçàôùúûîêäëïöüÿãñõœ]/;var aNumber=/[0-9]/;var aSpecial=/[ !@#$%^&*()\-\/_\'"§;.,:+\=]/;var Resultat=0;if(!$('#formPaperWallet #passPhrase').val())$('#messDangerPhrase').empty();else{var p=$('#formPaperWallet #passPhrase').val();var numUpper=0;var numLower=0;var numNums=0;var numSpecials=0;var numLongeur=p.length;var PassScore=0
for(var i=0;i<p.length;i++){if(anUpperCase.test(p[i]))numUpper++;else if(aLowerCase.test(p[i]))numLower++;else if(aNumber.test(p[i]))numNums++;else if(aSpecial.test(p[i]))numSpecials++;}
if(numLongeur<10)PassScore-=3;else PassScore+=Math.floor(numLongeur/10);if(numSpecials<1)PassScore-=1;else PassScore+=Math.floor(numSpecials/2);if(numUpper*10<numLongeur)PassScore-=Math.floor(numLongeur/20);else PassScore+=Math.floor(numUpper/3);if(numNums*10<numLongeur)PassScore-=Math.floor(numLongeur/20);else PassScore+=Math.floor(numNums/3);if(numLower*5<numLongeur)PassScore-=Math.floor(numLongeur/20);else PassScore+=Math.floor(numLower/4);if(PassScore<=20){$.m.user.messPass={"alert":"danger","icone":"ban","message":"PHRASE_DANGER"};$('#messDangerPhrase').empty().mustache('messDangerPhraseHTML',$.m);}
else if(PassScore<=40){$.m.user.messPass={"alert":"warning","icone":"exclamation-triangle","message":"PHRASE_WARNING"};$('#messDangerPhrase').empty().mustache('messDangerPhraseHTML',$.m);}
else{$.m.user.messPass={"alert":"success","icone":"check","message":"PHRASE_SUCCES"};$('#messDangerPhrase').empty().mustache('messDangerPhraseHTML',$.m);}}},}});})(jQuery);
(function($,undefined){$.extend({tmpl:{spinOn:function(e,i){$('#'+e).removeClass(i).addClass($.m.tmpl.html.spinClass);},spinOff:function(e,i){$('#'+e).removeClass($.m.tmpl.html.spinClass).addClass(i);},error:function(e){$.jGrowl($.lng.tr(e,true)+' ',{position:'bottom-right',closeTemplate:'<i class=\"fa fa-times\"></i>'});setTimeout(function(){$.voix.play($.m.voix.sound.error);},500);},msg:function(e){$.jGrowl($.lng.tr(e,true)+' ',{position:'bottom-right',closeTemplate:'<i class=\"fa fa-times\"></i>'});setTimeout(function(){$.voix.play($.m.voix.sound.click);},500);},clean:function(){window.scrollTo(0,0);$('.popover').remove();$('.tooltip').remove();},anim:function(e,effect,r,callback){e.addClass('animated '+effect);e.one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){if(r)e.removeClass('animated '+effect);if(callback)callback(e);});},niceNumber:function(e){return e.toString().replace(/(\d)(?=(?:\d{3})+(?:$))/g,'$1 ');},setupValidatorForm:function(){jQuery.validator.setDefaults({rules:$.m.tmpl.rules,messages:$.m.tmpl.messages,errorClass:"help-block",errorElement:"small",errorPlacement:function(error,e){error.appendTo($(e).parents(".form-group"));},showErrors:function(errorMap,errorList){$.each(errorList,function(key,val){val.message=$.lng.tr(val.message,true);});this.defaultShowErrors();},highlight:function(e,errorClass,validClass){$(e).parents('.form-group').addClass('has-error');$(e).parents('.form-group').removeClass('has-success');},unhighlight:function(e,errorClass,validClass){$(e).parents('.form-group').removeClass('has-error');$(e).parents('.form-group').addClass('has-success');},submitHandler:function(form){$('#'+form.id).trigger(form.id);}});},},lng:{get:function(){if(!$.m.lng.langue){var lngCookie=$.cookie($.m.lng.cookie);if(lngCookie!=undefined){if($.inArray(lngCookie,$.m.lng.list)>-1)$.m.lng.langue=lngCookie;else{$.m.lng.langue=$.m.lng.list[0];$.cookie($.m.lng.cookie,$.m.lng.langue);}}
else{if($.inArray($.linguaGetLanguage(),$.m.lng.list)>-1)$.m.lng.langue=$.linguaGetLanguage();else $.m.lng.langue=$.m.lng.list[0];$.cookie($.m.lng.cookie,$.m.lng.langue);}}
return $.m.lng.langue;},tr:function(e,p){var transit=$.lingua(e);if(!transit)transit=e;if(p)return'<span class="langTr" data-langue="'+e+'">'+transit+'</span>';else return transit;},tx:function(e){var result='';$.each(e,function(key,val){if($.lng.get()==key)result=val;});if(!result)result=e[Object.keys(e)[0]];return result;},changeLangue:function(param){if($.inArray(param,$.m.lng.list)>-1){if($.m.lng.langue!=param){$.m.lng.langue=param;$.linguaLoad($.m.lng.langue);$.cookie($.m.lng.cookie,$.m.lng.langue);moment.lang($.m.lng.langue);$('.langTr').each(function(){$(this).fadeOut(400,function(){$(this).text($.lng.tr($(this).data('langue')));$(this).fadeIn(400);});});$('[data-tr]').each(function(){$(this).attr('data-original-title',$.lng.tr($(this).data('tr')));});$('#icoLangue').fadeOut(400,function(){$(this).attr({src:$.m.lng.root+$.m.lng.langue+$.m.lng.extension,alt:$.m.lng.langue}).parent().attr("data-original-title",$.lng.tr($.m.lng.langue));$(this).fadeIn(400);});$('#'+$.m.div.event).trigger($.m.event.langue);}}},},voix:{init:function(){if($.m.voix.is){if(!$.m.voix.load.sound){$.ionSound({sounds:$.m.voix.sound.list,path:$.m.voix.sound.url,multiPlay:true});$.m.voix.load.sound=true;}
setTimeout(function(){$.voix.btnSound();},3000);}},play:function(str){if($.m.voix.is){$.ionSound.play(str);}},toggle:function(){if($.m.voix.is){$.m.voix.is=false;$.cookie('voixSound',0);$('#mSound').removeClass('btn-primary').addClass('btn-primary');$('#mSound i').removeClass('fa-volume-up').addClass('fa-volume-off');}
else{$.m.voix.is=true;$.voix.init();$.cookie('voixSound',1);$.voix.play($.m.voix.sound.click);$('#mSound').removeClass('btn-primary').addClass('btn-primary');$('#mSound i').removeClass('fa-volume-off').addClass('fa-volume-up');}},btnSound:function(){$('#'+$.m.div.menu+' .btn').each(function(){$(this).mouseenter(function(){$.voix.play($.m.voix.sound.btnOver);});});},}});})(jQuery);$(function(){$.getJSON("js/boot.json",function(e){$.extend({m:e});$.jsonRPC.setup({endPoint:$.m.api,namespace:''});$.linguaInit($.m.lng.url,$.m.lng.file);$.linguaLoad($.lng.get());moment.lang($.lng.get());$.jGrowl.defaults.closerTemplate='';$.m.T=function(){return function(text,render){return $.lng.tr(render(text),true)}};$.m.TX=function(){return function(text,render){return $.lng.tr(render(text))}};$.m.FROMNOW=function(){return function(text,render){return'<span class="timeFromNow" data-timestamp="'+render(text)+'">'+moment(render(text),'X').fromNow()+'</span>'}};$.m.LLLL=function(){return function(text,render){return moment(render(text),'X').format('LLLL')}};$.m.YMD=function(){return function(text,render){return moment(render(text),'X').format('YYYY/MM/DD')}};$.m.H=function(){return function(text,render){return moment(render(text),'X').format('HH:mm')}};$.m.NICE_NUMBER=function(){return function(text,render){return render(text).toString().replace(/(\d)(?=(?:\d{3})+(?:$))/g,'$1 ');}};$.Mustache.load('js/boot.htm').done(function(){$.tmpl.setupValidatorForm();$('#'+$.m.div.event).on('login',function(){if($.m.voix.is)$.voix.init();});$('#'+$.m.div.event).on('logout',function(){if($.m.voix.is)$.voix.init();});var cook=$.cookie('voixSound');if(cook!=undefined&&cook==1){$.m.voix.is=true;}
$.voix.init();$('#'+$.m.div.menu).mustache('mVoix',$.m);$('#'+$.m.div.menu).mustache('mLangue',$.m,{method:'prepend'});$('#menu button').tooltip();setInterval(function(){$('.timeFromNow').each(function(){$(this).text(moment($(this).data('timestamp'),'X').fromNow());});},60000);$.each($.m.plug.list,function(key,val){$.getJSON($.m.plug.url+val+'/'+val+'.json',function(data){$.m[val]=data;$.Mustache.load($.m.plug.url+val+'/'+val+'.htm').done(function(){$[val].setup();});});});});});});